name: Pull Request Test && Merge
on: [push]
jobs:
  install:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm-256color
      COLORTERM: truecolor
    steps:
      - name: Install Docker
        if: matrix.os == 'macos-latest'
        run: |
          brew install --cask docker
          docker_app_path=$(brew list --cask docker | grep '==> App' -A1 | tail -n 1 | awk '{ print $1 }')
          docker_app_path="${docker_app_path/#\~/$HOME}"
          sudo "$docker_app_path"/Contents/MacOS/Docker --unattended --install-privileged-components
          open -a "$docker_app_path" --args --unattended --accept-license
          while ! "$docker_app_path"/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
          # Wait for the server to start up, if applicable.
          i=0
          while ! docker system info &>/dev/null; do
            (( i++ == 0 )) && printf %s '-- Waiting for Docker to finish starting up...' || printf '.'
            sleep 1
          done
          (( i )) && printf '\n'
          # https://github.com/actions/virtual-environments/issues/1143#issuecomment-652264388
          echo "-- Docker is ready."
      - name: run REI install
        run: |
          bash rei.sh --yes
      - run: echo "🍏 This job's status is ${{ job.status }}."
